site_name: Invenio
site_dir: _site
site_url: https://invenio.front-matter.io
repo_url: https://github.com/front-matter/invenio
edit_uri: edit/main/docs/
repo_name: front-matter/invenio
copyright: Copyright &copy; 2025 Front Matter
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
theme:
  name: material
  custom_dir: docs
  logo: assets/invenio.png
  palette:    
    - media: "(prefers-color-scheme: light)"
      scheme: starter-light
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - content.code.copy
    - content.action.edit
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<info@front-matter.io>
    - icon: fontawesome/brands/mastodon 
      link: https://hachyderm.io/@mfenner
    - icon: fontawesome/brands/github
      link: https://github.com/front-matter/invenio
extra_css:
  - stylesheets/extra.css
